export type BattingStat = {
  id: number;
  player_id: number;
  player_name: string;
  player_position: string;
  game_result: string;
  game_date: string;
  opponent_name: string;
  game_id: number;
  ab: number;
  pa: number;
  runs: number;
  hits: number;
  rbi: number;
  bb: number;
  so: number;
  hbp: number;
  ibb: number;
  sb: number;
  cs: number;
  dp: number;
  double: number;
  triple: number;
  hr: number;
  sf: number;
  sh: number;
  picked_off: number;
  avg: number;
  obp: number;
  slg: number;
  hrpct: number;
  bbpct: number;
  kpct: number;
  ab_per_hr: number;
  babip: number;
  tb: number;
  box_score_link: number;
};
// Since this will be used for columns, we only want to include column stats
export type BattingSituationalStat = {
  player_name: string;
  player_id: number;
  school: string;
  with_runners: JSON;
  hits_with_risp: {
    H: number;
    AB: number;
  };
  vs_lhp: {
    H: number;
    AB: number;
  };

  vs_rhp: JSON;
  leadoff_pct: JSON;
  rbi_runner_on_3rd: JSON;
  h_pinchhit: JSON;
  runners_advanced: JSON;
  with_two_outs: JSON;
  with_two_runners: JSON;
  with_two_in_scoring: JSON;
  bases_empty: JSON;
  bases_loaded: JSON;
};
export type PitchingStat = {
  id: number;
  game_date: Date;
  game_result: string;
  opponent_name: string;
  decision: string;
  box_score_link: number;
  player_id: number;
  player_name: string;
  jersey_number: string;
  ip: number;
  h: number;
  r: number;
  er: number;
  bb: number;
  so: number;
  bf: number;
  doubles_allowed: number;
  triples_allowed: number;
  hr_allowed: number;
  wp: number;
  hb: number;
  starter: number;
  ibb: number;
  balk: number;
  ir: number;
  irs: number;
  sh_allowed: number;
  sf_allowed: number;
  kl: number;
  pickoffs: number;
  wins: number;
  losses: number;
  saves: number;
  ab: number;
  era: number;
  whip: number;
  games: number;
};

export type FieldingStat = {
  id: number;
  player_name: string;
  player_id: number;
  game_date: Date;
  opponent_name: string;
  game_result: string;
  game_id: number;
  player_position: string;
  po: number;
  a: number;
  e: number;
  cum_fcpt: number;
  catchers_interference: number;
  passed_balls: number;
  sba: number;
  cs: number;
  dp: number;
  tp: number;
};

export type AllBattingStat = {
  id: number;
  player_id: number;
  total_hits: number;
  player_name: string;
  jersey_number: number;
  player_position: JSON;
  total_team_games: number;
  total_ab: number;
  total_pa: number;
  total_runs: number;
  total_rbi: number;
  total_bb: number;
  total_strikeouts: number;
  total_hbp: number;
  total_ibb: number;
  total_sb: number;
  total_cs: number;
  total_dp: number;
  total_double: number;
  total_triple: number;
  total_hr: number;
  total_sf: number;
  total_sh: number;
  total_picked_off: number;
  avg: number;
  obp: number;
  tb: number;
  slg: number;
  ops: number;
  games: number;
};

export type AllPitchingStat = {
  id: number;
  player_id: number;
  player_name: string;
  jersey_number: number;
  total_team_games: number;
  total_outs: number;
  total_h: number;
  total_r: number;
  total_er: number;
  total_bb: number;
  total_so: number;
  total_bf: number;
  total_doubles_allowed: number;
  total_triples_allowed: number;
  total_hr_allowed: number;
  total_wp: number;
  total_hb: number;
  total_starts: number;
  total_ibb: number;
  total_balk: number;
  total_ir: number;
  total_irs: number;
  total_sh_allowed: number;
  total_sf_allowed: number;
  total_kl: number;
  total_pickoffs: number;
  total_wins: number;
  total_losses: number;
  total_saves: number;
  total_ab: number;
  total_era: number;
  total_whip: number;
  total_games: number;
};

export type AllFieldingStatByPos = {
  player_name: string;
  player_id: number;
  player_position: string;
  total_po: number;
  total_a: number;
  total_e: number;
  total_catchers_interference: number;
  total_passed_balls: number;
  total_sba: number;
  total_cs: number;
  total_dp: number;
  total_tp: number;
};

export type AllFieldingStatByPlayer = {
  player_name: string;
  player_id: number;
  player_position: string;
  total_team_games: number;
  total_player_games: number;
  jersey_number: number;
  total_po: number;
  total_a: number;
  total_e: number;
  total_catchers_interference: number;
  total_passed_balls: number;
  total_sba: number;
  total_cs: number;
  total_dp: number;
  total_tp: number;
  total_pa: number;
  all_positions: JSON;
};
