# Generated by Django 5.2.1 on 2025-05-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pitcherstat_balk_alter_pitcherstat_bb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitcherstat',
            old_name='save',
            new_name='sv',
        ),
    ]
