# Generated by Django 5.2.1 on 2025-05-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_fieldingstat_gameinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='attendance',
            field=models.IntegerField(),
        ),
    ]
