# Generated by Django 5.2.1 on 2025-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_gameinfo_selected_team_errors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='game_date',
            field=models.CharField(max_length=15),
        ),
    ]
