# Generated by Django 5.2.1 on 2025-05-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatterStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.IntegerField(max_length=12)),
                ('game_id', models.IntegerField(max_length=14)),
                ('ab', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('rbi', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('so', models.IntegerField()),
                ('hbp', models.IntegerField()),
                ('ibb', models.IntegerField()),
                ('sb', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('dp', models.IntegerField()),
                ('double', models.IntegerField()),
                ('triple', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('sf', models.IntegerField()),
                ('sh', models.IntegerField()),
                ('picked_off', models.IntegerField()),
            ],
        ),
    ]
