# Generated by Django 5.2.1 on 2025-05-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterstat',
            name='game_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='batterstat',
            name='player_id',
            field=models.IntegerField(),
        ),
    ]
