# Generated by Django 5.2.1 on 2025-05-23 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_batterstat_game_id_alter_batterstat_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100, unique=True)),
                ('player_position', models.CharField(max_length=7)),
                ('jersey_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='batterstat',
            name='player_id',
        ),
        migrations.AddField(
            model_name='batterstat',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.playerinfo'),
        ),
    ]
