# Generated by Django 5.2.1 on 2025-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_playerinfo_remove_batterstat_player_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitcherStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.IntegerField(max_length=12)),
                ('game_id', models.IntegerField(max_length=14)),
                ('starter', models.BooleanField()),
                ('ip', models.DecimalField(decimal_places=1, max_digits=4)),
                ('h', models.IntegerField(max_length=2)),
                ('r', models.IntegerField(max_length=2)),
                ('er', models.IntegerField(max_length=2)),
                ('bb', models.IntegerField(max_length=2)),
                ('so', models.IntegerField(max_length=2)),
                ('bf', models.IntegerField(max_length=2)),
                ('doubles_allowed', models.IntegerField(max_length=2)),
                ('triples_allowed', models.IntegerField(max_length=2)),
                ('hr_allowed', models.IntegerField(max_length=2)),
                ('wp', models.IntegerField(max_length=2)),
                ('hb', models.IntegerField(max_length=2)),
                ('ibb', models.IntegerField(max_length=2)),
                ('balk', models.IntegerField(max_length=2)),
                ('ir', models.IntegerField(max_length=2)),
                ('irs', models.IntegerField(max_length=2)),
                ('sh_allowed', models.IntegerField(max_length=2)),
                ('sf_allowed', models.IntegerField(max_length=2)),
                ('kl', models.IntegerField(max_length=2)),
                ('pickoffs', models.IntegerField(max_length=2)),
                ('win', models.BooleanField()),
                ('loss', models.BooleanField()),
                ('save', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='batterstat',
            old_name='player',
            new_name='player_id',
        ),
    ]
