# Generated by Django 5.2.1 on 2025-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pitcherstat_rename_player_batterstat_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcherstat',
            name='balk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='bb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='bf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='doubles_allowed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='er',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='game_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='h',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='hb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='hr_allowed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='ibb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='ir',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='irs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='kl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='pickoffs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='player_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='r',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='sf_allowed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='sh_allowed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='so',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='triples_allowed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='wp',
            field=models.IntegerField(),
        ),
    ]
