# Generated by Django 5.2.1 on 2025-05-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_save_pitcherstat_sv'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='weight',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
