# Generated by Django 5.2.1 on 2025-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_playerinfo_height_playerinfo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
