# Generated by Django 5.2.1 on 2025-05-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_playerinfo_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldingStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.IntegerField()),
                ('player_position', models.CharField(max_length=7)),
                ('game_id', models.IntegerField()),
                ('po', models.IntegerField()),
                ('a', models.IntegerField()),
                ('e', models.IntegerField()),
                ('catchers_interference', models.IntegerField()),
                ('pb', models.IntegerField()),
                ('sba', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('dp', models.IntegerField()),
                ('tp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_date', models.DateField()),
                ('selected_team', models.CharField(max_length=20)),
                ('opponent', models.CharField(max_length=20)),
                ('selected_team_home', models.BooleanField()),
                ('total_innings', models.IntegerField()),
                ('selected_team_runs', models.IntegerField()),
                ('opponent_runs', models.IntegerField()),
                ('selected_team_hits', models.IntegerField()),
                ('opponent_hits', models.IntegerField()),
                ('selected_team_errors', models.IntegerField()),
                ('opponent_errors', models.IntegerField()),
                ('selected_team_dpt', models.IntegerField()),
                ('opponent_dpt', models.IntegerField()),
                ('selected_team_tpt', models.IntegerField()),
                ('opponent_tpt', models.IntegerField()),
                ('winning_pitcher', models.CharField(max_length=20)),
                ('losing_pitcher', models.CharField(max_length=20)),
                ('save_pitcher', models.CharField(max_length=20)),
                ('box_score_link', models.CharField(max_length=200)),
                ('attendance', models.IntegerField(max_length=6)),
            ],
        ),
    ]
