# Generated by Django 5.2.1 on 2025-05-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_gameinfo_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='selected_team_errors',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='selected_team_hits',
            field=models.IntegerField(null=True),
        ),
    ]
