# Generated by Django 5.2.1 on 2025-05-24 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_gameinfo_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterstat',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gameinfo'),
        ),
        migrations.AlterField(
            model_name='batterstat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='batterstat',
            name='player_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.playerinfo'),
        ),
        migrations.AlterField(
            model_name='fieldingstat',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gameinfo'),
        ),
        migrations.AlterField(
            model_name='fieldingstat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fieldingstat',
            name='player_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.playerinfo'),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gameinfo'),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='player_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.playerinfo'),
        ),
    ]
