# Generated by Django 5.2.1 on 2025-05-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_batterstat_game_id_alter_batterstat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='player_position',
            field=models.JSONField(null=True),
        ),
    ]
