# Generated by Django 5.2.1 on 2025-05-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_playerinfo_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='player_position',
            field=models.JSONField(default=dict),
        ),
    ]
