# Generated by Django 5.2.1 on 2025-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_playerinfo_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='player_position',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
