# Generated by Django 5.2.1 on 2025-05-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_playerinfo_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='save_pitcher',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
