# Generated by Django 5.2.1 on 2025-05-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_gameinfo_save_pitcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
