# Generated by Django 5.2.1 on 2025-06-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_playerinfo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcherstat',
            name='loss',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='starter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='sv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='win',
            field=models.IntegerField(),
        ),
    ]
