# Generated by Django 5.2.1 on 2025-06-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_pitcherstat_loss_alter_pitcherstat_starter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcherstat',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='starter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='sv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pitcherstat',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
