# Generated by Django 5.2.1 on 2025-06-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_battingsituational'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingsituational',
            name='runner_string',
            field=models.CharField(default=''),
        ),
    ]
