# Generated by Django 5.2.1 on 2025-06-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_battingsituational_runner_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingsituational',
            name='runner_string',
            field=models.CharField(null=True),
        ),
    ]
