# Generated by Django 5.2.1 on 2025-06-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_battingsituational_runner_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battingsituational',
            name='runner_string',
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='w_runners',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='jersey_number',
            field=models.IntegerField(null=True),
        ),
    ]
