# Generated by Django 5.2.1 on 2025-06-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_battingsituational_runner_string_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battingsituational',
            old_name='w_runners',
            new_name='bases_empty',
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='bases_loaded',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='h_pinchhit',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='hits_with_risp',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='leadoff_pct',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='rbi_runner_on_3rd',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='runners_advanced',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='vs_lhp',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='vs_rhp',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='with_runners',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='with_two_in_scoring',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='with_two_outs',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='battingsituational',
            name='with_two_runners',
            field=models.JSONField(default={}),
        ),
    ]
