# Generated by Django 5.2.1 on 2025-06-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_schoolinfo_remove_pitcherstat_ip_pitcherstat_outs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='school_tricode',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
