# Generated by Django 5.2.1 on 2025-06-22 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_gameinfo_selected_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='selected_team_id',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='selected_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_team', to='app.schoolinfo'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='app.schoolinfo'),
        ),
    ]
